export const globalStyles = {
  containerWidth: {
    base: '100%',
    lg: '95%',
    xl: '1210px',
    '2xl': '1350px',
  },
  fullWidth: '100%',
  fullHeight: '100vh',
  primaryDarkColor: '#010821',
  primaryColor: '#010b2e',
  whiteColor: '#fff',
  lightFontWeight: 300,
  normalFontWeight: 400,
  semibold: 500,
  mediumbold: 600,
  bold: 700,
  smFontSize: '0.75rem',
  fontSize: '0.95rem', // 1rem = 16px
  textFontSize: '0.9rem',
  textOpacity: 0.8,
  hoverOpacity: { opacity: 0.5 },
  fontFamilyLight: 'Clash-display-light',
  fontFamilyXLight: 'Clash-display-extra-light',
  fontFamily: 'Clash-display',
  fontFamilyMedium: 'Clash-display-medium',
  fontFamilyBold: 'Clash-display-bold',
  fontFamilySemiBold: 'Clash-display-semibold',
};
